name: ocean-surface-wave-slopes-and-wind-wave-alignment
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20230802.0
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=14.0.2
  - async-lru=2.0.4
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.3
  - bokeh=3.4.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cairo=1.16.0
  - cartopy=0.22.0
  - certifi=2024.6.2
  - cffi=1.16.0
  - cfitsio=3.470
  - cftime=1.6.2
  - charset-normalizer=2.0.4
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.1
  - cmocean=4.0.3
  - colorcet=3.1.0
  - colorspacious=1.1.2
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cytoolz=0.12.2
  - dask=2024.5.0
  - dask-core=2024.5.0
  - dask-expr=1.1.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2024.5.0
  - exceptiongroup=1.2.0
  - expat=2.6.2
  - fiona=1.9.5
  - folium=0.14.0
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - freexl=2.0.0
  - fsspec=2024.3.1
  - gdal=3.6.2
  - geopandas=0.14.2
  - geopandas-base=0.14.2
  - geos=3.9.1
  - geotiff=1.7.0
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtest=1.14.0
  - hdf4=4.2.13
  - hdf5=1.12.1
  - heapdict=1.0.1
  - icu=73.1
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importnb=2023.11.1
  - ipywidgets=8.1.2
  - jinja2=3.1.4
  - joblib=1.4.0
  - jpeg=9e
  - json-c=0.16
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.10
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.7.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgdal=3.6.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libiconv=1.16
  - libkml=1.3.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libzip=1.8.0
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markupsafe=2.1.3
  - matplotlib-base=3.8.4
  - minizip=4.0.3
  - mistune=2.0.4
  - msgpack-python=1.0.3
  - mysql=5.7.24
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - netcdf4=1.6.2
  - networkx=3.2.1
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.3.0
  - openssl=3.0.14
  - orc=1.7.4
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.2.1
  - pandocfilters=1.5.0
  - partd=1.4.1
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.40.0
  - ply=3.11
  - poppler=22.12.0
  - poppler-data=0.4.11
  - proj=9.3.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=14.0.2
  - pybind11-abi=5
  - pycparser=2.21
  - pyparsing=3.0.9
  - pyproj=3.6.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-lmdb=1.4.1
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qhull=2020.2
  - qt-main=5.15.2
  - qtconsole=5.5.1
  - qtpy=2.4.1
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - rtree=1.0.1
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - send2trash=1.8.2
  - setuptools=69.5.1
  - shapely=2.0.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tblib=1.7.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tiledb=2.3.3
  - tinycss2=1.2.1
  - tk=8.6.14
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.3.3
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - uriparser=0.9.7
  - urllib3=2.2.1
  - utf8proc=2.6.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.10
  - xarray=2023.6.0
  - xerces-c=3.2.4
  - xyzservices=2022.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - appnope==0.1.3
      - asttokens==2.0.5
      - cattrs==23.2.3
      - comm==0.2.2
      - executing==0.8.3
      - ipykernel==6.29.3
      - ipython==8.25.0
      - jedi==0.19.1
      - jupyter-client==8.6.2
      - linearwavetheory==0.0.18
      - littlebuoybigwaves==0.1
      - llvmlite==0.43.0
      - matplotlib-inline==0.1.7
      - numba==0.60.0
      - numba-progress==1.1.0
      - parso==0.8.3
      - pdoc==14.6.0
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - pygments==2.18.0
      - requests-cache==1.2.1
      - roguewavespectrum==0.2.10
      - stack-data==0.6.2
      - tqdm==4.66.4
      - traitlets==5.14.3
      - typing-extensions==4.12.1
      - url-normalize==1.4.3
      - wcwidth==0.2.5
